### ISSUE TITLE
ESP is failing with ERROR:Fetching rollouts failed (status code 403, reason Forbidden, url https://servicemanagement.googleapis.com/v1/services/cbserviceaccount@steam-idiom-230308.iam.gserviceaccount.com/rollouts?filter=status=SUCCESS)

### ISSUE THREAD

**Issue by kvsravindrareddy** [GoogleCloudPlatform/java-docs-samples#1324]
ESP is failing with ERROR:Fetching rollouts failed (status code 403, reason Forbidden, url https://servicemanagement.googleapis.com/v1/services/cbserviceaccount@steam-idiom-230308.iam.gserviceaccount.com/rollouts?filter=status=SUCCESS).

i might be not correct to configure the service account. I am not sure how to create the SERVICE_NAME=hellogrpc.endpoints.${GCLOUD_PROJECT}.cloud.goog

**Comment by kurtisvg** [comment]
Hey @kvsravindrareddy,

Unfortunately there isn't enough information here to figure out which sample you were using or what is going wrong. In the future, please stick to using the provided issue template so that we can provide guidance more easily.

**Comment by fonylew** [comment]
I'm still experiencing this error. Referring to this post: https://groups.google.com/forum/#!topic/google-cloud-endpoints/xxqkH-mYcZc

**Comment by KOSSOKO** [comment]
Hi, i'm follwing the tutorial and and i'm experiencing the same thing: 

```
INFO:Fetching an access token from the metadata service
INFO:Fetching the service config ID from the rollouts service
ERROR:Fetching rollouts failed (status code 403, reason {
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED"
  }
```
}

**Comment by KOSSOKO** [comment]
@fonylew Did you find a solution ?

**Comment by bdesmarez** [comment]
@KOSSOKO I'm facing the same issue;
Contacting the support right now.
Did you find a solution on your side?
Thanks

**Comment by KOSSOKO** [comment]
@bdesmarez , you have to create a service account and load it inside you container.
The process: 
1- Generate json service account and create a secrets in kubernetes
kubectl create secret generic cloud-endpoints-credentials \
 --from-file=cloudendpoint.json=gara-endpoints-credentials.json

2- load it inside your container. You should have this deployment file:
```

apiVersion: v1
kind: Service
metadata:
  name: esp-echo
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: esp-echo
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-echo
    spec:
      containers:
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=echo-api.endpoints.gara-261618.cloud.goog",
          "--rollout_strategy=managed",
          "--service_account_key=/etc/nginx/creds/cloudendpoint.json"

        ]
        volumeMounts:
            - name: cloud-endpoints-credentials-volume
              mountPath: /etc/nginx/creds
              readOnly: true
      # [END esp]
        ports:
          - containerPort: 8081
      - name: echo
        image: gcr.io/google-samples/echo-java:1.0
        ports:
          - containerPort: 8080
      volumes:
        - name: cloud-endpoints-credentials-volume
          secret:
            secretName: cloud-endpoints-credentials




```
